### ISSUE TITLE
Baseline code

### ISSUE THREAD

**Issue by ciccio42** [jeffacce/play-to-policy#2]
Hello.
First of all, thanks for sharing, and congratulations for your work.
I would like to use your code as a baseline for my experiments about Conditioned Imitation Learning. However, while this repo contains the code of the proposed method, I would like to know if there is a possibility to share the code of the baselines used in your work, especially GTI, since there are no open-source implementations available, and your article does not specify how it was implemented, as you did with the other methods.

I appreciate your consideration.

Francesco Rosa.

**Comment by jeffacce** [comment]
Hi Francesco,

Thanks for your interest in our work. It would be best to contact the original GTI authors for a reference implementation. For the GTI baseline comparison, we implement Stage 1 in their paper (Figure 2 mid) with a cVAE for the goal network, and a transformer encoder for the policy network in lieu of the RNN. During rollout, we encode the target observation $s_g$ into $z_g$ with the cVAE for the low-level policy goal condition.

Best,
Jeff
