### ISSUE TITLE
What does parameters in Action mean?

### ISSUE THREAD

**Issue by RussRobin** [jeffacce/play-to-policy#3]
Hi, thank you for your wonderful work.

In RT-X version of your dataset (NYU Franka Play), I get :
data['steps'][0]['action'] = 
array([ 1.3448209e-02, -1.6239583e-03,  5.9485435e-05,  3.2937050e-02,
       -2.6911497e-05, -9.7005963e-02,  1.1165179e-03, -4.4397563e-03,
       -2.8908253e-04,  8.7654293e-03, -1.6401529e-02,  5.6316584e-02,
       -2.3147106e-02,  1.0000000e+00,  0.0000000e+00], dtype=float32)

What do these 15 parameters in 'action' mean?

Great thanks in advance for your help.

**Comment by jeffacce** [comment]
Hi there,

Thanks for your interest in our work!

The action dims are:

```
Joint velocities (7)
EE delta xyz (3)
EE delta rpy (3)
Gripper position (1)
Terminate episode (1)
```
